title: Saaransh Agarwal # your name (or website title) here
logo: "/images/pro_pic.jpg"
description: >
  Final Year UG || IIT Ropar, Btech in Mechanical Engineering with minor in Computer Science.
  <br>
  Primarily interested in Web Development and Competitive programming.
  <br>
  <a href="https://github.com/Prudhvipvp/prudhvipvp.github.io/blob/master/pdf/ResumePrudhvi%20(1).pdf">View My Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/prudhvi-paramkusam-b34079153/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/Prudhvipvp/">View my Github Profile
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
